import type { AppRole } from "@/lib/roles";
import type {
  Agency,
  ApprovalStatus,
  Parcel,
  Payment,
  Ticket,
  Zone,
} from "@/lib/domain";

/** Seed dataset for demo mode. Kept identical to umbrella/api/prisma/seed.ts. */

export type MockUser = {
  id: number;
  name: string;
  email: string;
  role: AppRole;
  phone: string;
  password: string;
  isActive: boolean;
  agencyId?: number | null;
  zoneId?: number | null;
  approvalStatus?: ApprovalStatus;
  governorate?: string | null;
  city?: string | null;
  address?: string | null;
  shopName?: string | null;
  productTypes?: string[];
  productNotes?: string | null;
  createdAt?: string;
};

export type MockParcel = Parcel & { code: string; price: number };
export type MockTicket = Ticket;
export type MockPayment = Payment & {
  amount: number;
  items: Array<{ parcel: { id: number; code: string | null }; amount: number }>;
};
export type MockZone = Zone;

export const MOCK_USERS: MockUser[] = [
  {
    id: 1,
    name: "Super Admin",
    email: "super@umbrella.tn",
    role: "SUPER_ADMIN",
    phone: "20000001",
    password: "Super@12345",
    isActive: true,
    approvalStatus: "APPROVED",
  },
  {
    id: 2,
    name: "Umbrella Admin",
    email: "admin@umbrella.tn",
    role: "ADMIN",
    phone: "20000000",
    password: "Admin@12345",
    isActive: true,
    approvalStatus: "APPROVED",
  },
  {
    id: 3,
    name: "Demo Expéditeur",
    email: "expediteur@umbrella.tn",
    role: "EXPEDITEUR",
    phone: "57120677",
    password: "Expediteur@12345",
    isActive: true,
    approvalStatus: "APPROVED",
    shopName: "Demo Boutique",
    productTypes: ["Vêtements", "Accessoires"],
    governorate: "Tunis",
    city: "Tunis",
    address: "12 Avenue Habib Bourguiba",
  },
  {
    id: 4,
    name: "Demo Livreur",
    email: "livreur@umbrella.tn",
    role: "LIVREUR",
    phone: "22000000",
    password: "Livreur@12345",
    isActive: true,
    approvalStatus: "APPROVED",
    zoneId: 1,
    governorate: "Tunis",
    city: "La Marsa",
    address: "Route de La Marsa",
  },
  {
    id: 5,
    name: "Demo Client",
    email: "client@umbrella.tn",
    role: "CLIENT",
    phone: "51926850",
    password: "Client@12345",
    isActive: true,
    approvalStatus: "APPROVED",
  },
  {
    id: 6,
    name: "Karim Ben Salah",
    email: "livreur2@umbrella.tn",
    role: "LIVREUR",
    phone: "22000001",
    password: "Livreur@12345",
    isActive: true,
    approvalStatus: "APPROVED",
    zoneId: 1,
    governorate: "Tunis",
    city: "Ariana",
    address: "Cité Ennasr",
  },
  {
    id: 7,
    name: "Chef Agence Tunis",
    email: "chef@umbrella.tn",
    role: "CHEF_AGENCE",
    phone: "23000001",
    password: "Chef@12345",
    isActive: true,
    approvalStatus: "APPROVED",
    agencyId: 1,
  },
  {
    id: 8,
    name: "Support Retours Tunis",
    email: "support@umbrella.tn",
    role: "SUPPORT",
    phone: "23000002",
    password: "Support@12345",
    isActive: true,
    approvalStatus: "APPROVED",
    agencyId: 1,
  },
  {
    id: 9,
    name: "Pickup Tunis",
    email: "pickup@umbrella.tn",
    role: "PICKUP",
    phone: "23000003",
    password: "Pickup@12345",
    isActive: true,
    approvalStatus: "APPROVED",
    agencyId: 1,
  },
  {
    id: 10,
    name: "Magasinier Tunis",
    email: "magasinier@umbrella.tn",
    role: "MAGASINIER",
    phone: "23000004",
    password: "Magasin@12345",
    isActive: true,
    approvalStatus: "APPROVED",
    agencyId: 1,
  },
  {
    id: 11,
    name: "Finance Umbrella",
    email: "finance@umbrella.tn",
    role: "FINANCE",
    phone: "24000001",
    password: "Finance@12345",
    isActive: true,
    approvalStatus: "APPROVED",
  },
];

export const MOCK_AGENCIES: Agency[] = [
  {
    id: 1,
    name: "Agence Tunis",
    governorate: "Tunis",
    isActive: true,
  },
  {
    id: 2,
    name: "Agence Sousse",
    governorate: "Sousse",
    isActive: true,
  },
  {
    id: 3,
    name: "Agence Sfax",
    governorate: "Sfax",
    isActive: true,
  },
];

const day = (offset: number) => {
  const d = new Date();
  d.setDate(d.getDate() - offset);
  return d.toISOString();
};

export const MOCK_ZONES: MockZone[] = [
  {
    id: 1,
    name: "Zone Tunis",
    governorate: "Tunis",
    centerLat: null,
    centerLng: null,
    radiusKm: 20,
    isActive: true,
  },
  {
    id: 2,
    name: "Zone B",
    governorate: null,
    centerLat: null,
    centerLng: null,
    radiusKm: null,
    isActive: true,
  },
  {
    id: 3,
    name: "Zone C",
    governorate: "Sfax",
    centerLat: 34.7478,
    centerLng: 10.7662,
    radiusKm: 30,
    isActive: true,
  },
];

export const MOCK_PARCELS: MockParcel[] = [
  {
    id: 1,
    code: "UMB-ATT-001",
    recipientName: "Demo Client",
    phone: "51926850",
    governorate: "Ariana",
    city: "Ariana",
    address: "Cité Ennasr 2",
    price: 49.9,
    notes: "Parfum",
    designation: "Parfum",
    status: "EN_ATTENTE",
    mode: "EXTERNAL",
    bordereauUrl: "https://example.com/bordereau.pdf",
    createdAt: day(1),
    senderId: 3,
    timeline: [
      { at: day(1), label: "Colis créé" },
      { at: day(1), label: "En attente d'enlèvement" },
    ],
  },
  {
    id: 2,
    code: "UMB-COURS-001",
    recipientName: "Demo Client",
    phone: "51926850",
    governorate: "Tunis",
    city: "Tunis",
    address: "Avenue Habib Bourguiba 12",
    price: 55,
    notes: "Livres",
    designation: "Livres",
    status: "EN_COURS",
    mode: "INTERNAL",
    bordereauUrl: null,
    createdAt: day(0),
    senderId: 3,
    driverId: 4,
    driver: { id: 4, name: "Demo Livreur" },
    zone: { id: 1, name: "Zone A" },
    timeline: [
      { at: day(2), label: "Colis créé" },
      { at: day(1), label: "Enlevé" },
      { at: day(0), label: "En cours de livraison" },
    ],
  },
  {
    id: 3,
    code: "UMB-LIV-001",
    recipientName: "Demo Client",
    phone: "51926850",
    governorate: "Tunis",
    city: "La Marsa",
    address: "Corniche",
    price: 45.5,
    notes: "Demo paiement",
    designation: "Accessoires",
    status: "LIVRES",
    mode: "INTERNAL",
    bordereauUrl: null,
    createdAt: day(4),
    senderId: 3,
    driverId: 4,
    driver: { id: 4, name: "Demo Livreur" },
    zone: { id: 1, name: "Zone A" },
    timeline: [
      { at: day(5), label: "Colis créé" },
      { at: day(4), label: "Livré" },
    ],
  },
  {
    id: 4,
    code: "UMB-ENL-001",
    recipientName: "Amira Trabelsi",
    phone: "51926850",
    governorate: "Ben Arous",
    city: "Ezzahra",
    address: "Avenue Habib Bourguiba",
    price: 28,
    notes: "Vêtements",
    status: "A_ENLEVER",
    mode: "INTERNAL",
    bordereauUrl: null,
    createdAt: day(2),
    senderId: 3,
    driverId: 4,
    driver: { id: 4, name: "Demo Livreur" },
    zone: { id: 1, name: "Zone A" },
  },
  {
    id: 5,
    code: "UMB-ECH-001",
    recipientName: "Demo Client",
    phone: "51926850",
    governorate: "Mahdia",
    city: "Ksour Essaf",
    address: "Rue 54 Amilcar",
    price: 22,
    notes: "Échange taille",
    status: "ECHANGES",
    mode: "INTERNAL",
    bordereauUrl: null,
    createdAt: day(6),
    senderId: 3,
    driverId: 4,
    driver: { id: 4, name: "Demo Livreur" },
  },
  {
    id: 6,
    code: "UMB-DEP-001",
    recipientName: "Hedi Mansouri",
    phone: "51926850",
    governorate: "Sfax",
    city: "Sfax",
    address: "Route de Gabès km 3",
    price: 95,
    notes: "Pièces auto",
    status: "AU_DEPOT",
    mode: "INTERNAL",
    bordereauUrl: null,
    createdAt: day(3),
    senderId: 3,
    driverId: 6,
    driver: { id: 6, name: "Karim Ben Salah" },
    zone: { id: 3, name: "Zone C" },
  },
  {
    id: 7,
    code: "UMB-EXT-001",
    recipientName: "Sami Gharbi",
    phone: "51926850",
    governorate: "Sousse",
    city: "Sousse",
    address: "Boulevard 14 Janvier",
    price: 120,
    notes: "Tablette",
    status: "AU_DEPOT",
    mode: "EXTERNAL",
    bordereauUrl: "https://example.com/bordereau-ext.pdf",
    createdAt: day(2),
    senderId: 3,
  },
  {
    id: 8,
    code: "UMB-RET-001",
    recipientName: "Inconnu",
    phone: "51926850",
    governorate: "Kairouan",
    city: "Kairouan",
    address: "Adresse incomplete",
    price: 40,
    notes: "Retour",
    status: "RETOUR_DEFINITIF",
    mode: "EXTERNAL",
    bordereauUrl: null,
    createdAt: day(10),
    senderId: 3,
  },
  {
    id: 9,
    code: "UMB-LIVP-001",
    recipientName: "Demo Client",
    phone: "51926850",
    governorate: "Ariana",
    city: "Raoued",
    address: "Route de Bizerte",
    price: 67,
    notes: "Cosmétiques",
    status: "LIVRES_PAYES",
    mode: "EXTERNAL",
    bordereauUrl: null,
    createdAt: day(8),
    senderId: 3,
  },
  {
    id: 10,
    code: "UMB-VERIF-001",
    recipientName: "Nour Ben Ali",
    phone: "51926850",
    governorate: "Bizerte",
    city: "Bizerte",
    address: "Avenue Habib Thameur",
    price: 88,
    notes: "Montre",
    status: "A_VERIFIER",
    mode: "EXTERNAL",
    bordereauUrl: null,
    createdAt: day(5),
    senderId: 3,
  },
  {
    id: 11,
    code: "UMB-LIV-002",
    recipientName: "Salma Jebali",
    phone: "51926850",
    governorate: "Tunis",
    city: "Le Bardo",
    address: "Avenue de la République",
    price: 52,
    notes: "Parfum",
    status: "LIVRES",
    mode: "INTERNAL",
    bordereauUrl: null,
    createdAt: day(1),
    senderId: 3,
    driverId: 4,
    driver: { id: 4, name: "Demo Livreur" },
    zone: { id: 1, name: "Zone A" },
  },
  {
    id: 12,
    code: "UMB-LIV-003",
    recipientName: "Youssef Khelifi",
    phone: "51926850",
    governorate: "Nabeul",
    city: "Hammamet",
    address: "Zone touristique",
    price: 39.5,
    notes: "Chaussures",
    status: "LIVRES",
    mode: "INTERNAL",
    bordereauUrl: null,
    createdAt: day(2),
    senderId: 3,
    driverId: 4,
    driver: { id: 4, name: "Demo Livreur" },
    zone: { id: 1, name: "Zone A" },
  },
  {
    id: 13,
    code: "UMB-LIVP-002",
    recipientName: "Demo Client",
    phone: "51926850",
    governorate: "Ben Arous",
    city: "Rades",
    address: "Cité El Amal",
    price: 74,
    notes: "Électroménager",
    status: "LIVRES_PAYES",
    mode: "EXTERNAL",
    bordereauUrl: null,
    createdAt: day(3),
    senderId: 3,
  },
  {
    id: 14,
    code: "UMB-LIFE-001",
    recipientName: "Sana Mejri",
    phone: "51926850",
    governorate: "Tunis",
    city: "Tunis",
    address: "Centre ville — demo cycle livraison",
    price: 35,
    notes: "Demo cycle 1 (livraison)",
    designation: "Demo lifecycle",
    status: "EN_ATTENTE",
    mode: "INTERNAL",
    bordereauUrl: null,
    createdAt: day(0),
    senderId: 3,
    zone: { id: 1, name: "Zone A" },
    timeline: [{ at: day(0), label: "Colis créé" }],
  },
  {
    id: 15,
    code: "UMB-LIFE-002",
    recipientName: "Karim Ayari",
    phone: "51926850",
    governorate: "Tunis",
    city: "Tunis",
    address: "Lac 2 — demo cycle retour",
    price: 42,
    notes: "Demo cycle 2 (annulation / retour)",
    designation: "Demo return lifecycle",
    status: "EN_COURS",
    mode: "INTERNAL",
    bordereauUrl: null,
    createdAt: day(0),
    senderId: 3,
    driverId: 4,
    driver: { id: 4, name: "Demo Livreur" },
    zone: { id: 1, name: "Zone A" },
    timeline: [
      { at: day(2), label: "Colis créé" },
      { at: day(1), label: "Arrivé au dépôt" },
      { at: day(0), label: "En cours de livraison" },
    ],
  },
];

export const MOCK_TICKETS: MockTicket[] = [
  {
    id: 1,
    title: "Colis endommagé à la livraison",
    description: "Le carton était ouvert.",
    status: "EN_COURS",
    createdAt: day(1),
    parcel: { id: 3, code: "UMB-LIV-001" },
    createdBy: { id: 5, name: "Demo Client", email: "client@umbrella.tn" },
  },
  {
    id: 2,
    title: "Retard de livraison Sahel",
    description: "Client relance depuis 48h.",
    status: "EN_COURS",
    createdAt: day(2),
    parcel: { id: 2, code: "UMB-COURS-001" },
    createdBy: {
      id: 3,
      name: "Demo Expéditeur",
      email: "expediteur@umbrella.tn",
    },
  },
  {
    id: 3,
    title: "Changement d’adresse",
    description: "Passer à Cité Ennasr.",
    status: "RESOLU",
    createdAt: day(4),
    parcel: { id: 1, code: "UMB-ATT-001" },
    createdBy: { id: 5, name: "Demo Client", email: "client@umbrella.tn" },
  },
];

export const MOCK_PAYMENTS: MockPayment[] = [
  {
    id: 1,
    amount: 100.5,
    status: "EN_DEMANDE",
    note: "Demande COD",
    createdAt: day(1),
    sender: { name: "Demo Expéditeur", email: "expediteur@umbrella.tn" },
    items: [
      { parcel: { id: 3, code: "UMB-LIV-001" }, amount: 45.5 },
      { parcel: { id: 9, code: "UMB-LIVP-001" }, amount: 55 },
    ],
  },
  {
    id: 2,
    amount: 67,
    status: "PAYE",
    note: "Déjà réglé",
    createdAt: day(7),
    sender: { name: "Demo Expéditeur", email: "expediteur@umbrella.tn" },
    items: [{ parcel: { id: 9, code: "UMB-LIVP-001" }, amount: 67 }],
  },
  {
    id: 3,
    amount: 95,
    status: "APPROUVE",
    note: "En attente versement",
    createdAt: day(2),
    sender: { name: "Demo Expéditeur", email: "expediteur@umbrella.tn" },
    items: [{ parcel: { id: 6, code: "UMB-DEP-001" }, amount: 95 }],
  },
];

